### ISSUE TITLE
Error when loading first page.

### ISSUE THREAD

**Issue by Crsuh2er0** [yfszzx/stable-diffusion-webui-images-browser#11]
When I clicked on "First Page" button, this error happened:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 276, in run_predict
    fn_index, raw_input, username, session_state, iterators
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 787, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 695, in call_function
    block_fn.fn, *processed_input, limiter=self.limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/extensions/images-browser/scripts/images_history.py", line 184, in first_page_click
    return get_recent_images(1, 0, filenames)
  File "/content/stable-diffusion-webui/extensions/images-browser/scripts/images_history.py", line 150, in get_recent_images
    max_page_index = len(filenames) // num_of_imgs_per_page + 1
TypeError: object of type 'NoneType' has no len()`

**Comment by yfszzx** [comment]
try to pull the new edition

**Comment by Crsuh2er0** [comment]
Now its ok.
