### ISSUE TITLE
Crash on install

### ISSUE THREAD

**Issue by DylanSpeiser** [yfszzx/stable-diffusion-webui-images-browser#22]
I tried installing the extension but it causes the webUI to crash and not start. Happens even when there are no other extensions installed. Here is the log:
```venv "C:\Users\Dylan\Documents\StableDiffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: f53ca516385cddf07c4429720e6bd373547e9112
Installing requirements for Web UI
Launching Web UI with arguments: --disable-safe-unpickle --share --ckpt nai.ckpt --deepdanbooru
Checkpoint in --ckpt argument not found (Possible it was moved to C:\Users\Dylan\Documents\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion: nai.ckpt
Loading config from: C:\Users\Dylan\Documents\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\sd-v1-5.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [a9263745] from C:\Users\Dylan\Documents\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\sd-v1-5.ckpt
Global Step: 840000
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Traceback (most recent call last):
  File "C:\Users\Dylan\Documents\StableDiffusion\stable-diffusion-webui\modules\script_callbacks.py", line 47, in ui_settings_callback
    c.callback()
AttributeError: 'function' object has no attribute 'callback'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dylan\Documents\StableDiffusion\stable-diffusion-webui\launch.py", line 206, in <module>
    start_webui()
  File "C:\Users\Dylan\Documents\StableDiffusion\stable-diffusion-webui\launch.py", line 201, in start_webui
    webui.webui()
  File "C:\Users\Dylan\Documents\StableDiffusion\stable-diffusion-webui\webui.py", line 132, in webui
    demo = modules.ui.create_ui(wrap_gradio_gpu_call=wrap_gradio_gpu_call)
  File "C:\Users\Dylan\Documents\StableDiffusion\stable-diffusion-webui\modules\ui.py", line 1471, in create_ui
    script_callbacks.ui_settings_callback()
  File "C:\Users\Dylan\Documents\StableDiffusion\stable-diffusion-webui\modules\script_callbacks.py", line 49, in ui_settings_callback
    report_exception(c, 'ui_settings_callback')
  File "C:\Users\Dylan\Documents\StableDiffusion\stable-diffusion-webui\modules\script_callbacks.py", line 8, in report_exception
    print(f"Error executing callback {job} for {c.script}", file=sys.stderr)
AttributeError: 'function' object has no attribute 'script'```

**Comment by DylanSpeiser** [comment]
Update: it has something to do with the following calls on lines 322 and 323 of `images_history.py`:
```
script_callbacks.on_ui_settings(on_ui_settings)
script_callbacks.on_ui_tabs(on_ui_tabs)
```

**Comment by yfszzx** [comment]
git pull webui

**Comment by DylanSpeiser** [comment]
thank you for the help.
