### ISSUE TITLE
Attribute error at start with this extension

### ISSUE THREAD

**Issue by Leonovers** [yfszzx/stable-diffusion-webui-images-browser#9]
without this extension webui works, but with it crashes at start with this errors:

`Traceback (most recent call last):
  File "/home/leonovers/stable-diffusion-webui/modules/script_callbacks.py", line 47, in ui_settings_callback
    c.callback()
AttributeError: 'function' object has no attribute 'callback'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leonovers/stable-diffusion-webui/launch.py", line 206, in <module>
    start_webui()
  File "/home/leonovers/stable-diffusion-webui/launch.py", line 201, in start_webui
    webui.webui()
  File "/home/leonovers/stable-diffusion-webui/webui.py", line 132, in webui
    demo = modules.ui.create_ui(wrap_gradio_gpu_call=wrap_gradio_gpu_call)
  File "/home/leonovers/stable-diffusion-webui/modules/ui.py", line 1471, in create_ui
    script_callbacks.ui_settings_callback()
  File "/home/leonovers/stable-diffusion-webui/modules/script_callbacks.py", line 49, in ui_settings_callback
    report_exception(c, 'ui_settings_callback')
  File "/home/leonovers/stable-diffusion-webui/modules/script_callbacks.py", line 8, in report_exception
    print(f"Error executing callback {job} for {c.script}", file=sys.stderr)
AttributeError: 'function' object has no attribute 'script'`

**Comment by psdwizzard** [comment]
I am having the same issues as well

Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Commit hash: 91c1e1e6a92061b99c92a5b1d548535907d2ad96
Installing requirements for Web UI
Launching Web UI with arguments: --listen
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [318a302e] from C:\Users\kloeb\Downloads\SD\NovelAI\models\Stable-diffusion\arcane-diffusion-v3.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Traceback (most recent call last):
  File "C:\Users\kloeb\Downloads\SD\NovelAI\modules\script_callbacks.py", line 47, in ui_settings_callback
    c.callback()
AttributeError: 'function' object has no attribute 'callback'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kloeb\Downloads\SD\NovelAI\launch.py", line 206, in <module>
    start_webui()
  File "C:\Users\kloeb\Downloads\SD\NovelAI\launch.py", line 201, in start_webui
    webui.webui()
  File "C:\Users\kloeb\Downloads\SD\NovelAI\webui.py", line 132, in webui
    demo = modules.ui.create_ui(wrap_gradio_gpu_call=wrap_gradio_gpu_call)
  File "C:\Users\kloeb\Downloads\SD\NovelAI\modules\ui.py", line 1471, in create_ui
    script_callbacks.ui_settings_callback()
  File "C:\Users\kloeb\Downloads\SD\NovelAI\modules\script_callbacks.py", line 49, in ui_settings_callback
    report_exception(c, 'ui_settings_callback')
  File "C:\Users\kloeb\Downloads\SD\NovelAI\modules\script_callbacks.py", line 8, in report_exception
    print(f"Error executing callback {job} for {c.script}", file=sys.stderr)
AttributeError: 'function' object has no attribute 'script'
Press any key to continue . . .
Terminate batch job (Y/N)?

**Comment by yfszzx** [comment]
this is a problem of webui , it has fixed,run  "git pull"
